FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow==2.16.2

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:////app/mlflow.db", "--default-artifact-root", "file:///app/mlruns", "--host", "0.0.0.0", "--port", "5000"]