services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlops-mlflow
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mlops-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_MODEL_NAME=telco_churn_classifier
    depends_on:
      - mlflow
    volumes:
      - .:/app
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: mlops-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    restart: unless-stopped